![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [39]:
# Import necessary packages
import pandas as pd
import numpy as np

# Begin coding here ...
# Use as many cells as you like

# Loading data

In [40]:
# importing spreadsheet
file = 'data/airbnb_room_type.xlsx'
data = pd.ExcelFile(file)
df_room_type = data.parse()
df_room_type
df_room_type.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   description  25199 non-null  object
 2   room_type    25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB

In [41]:
# importing csv
file = 'data/airbnb_price.csv'
df_price = pd.read_csv(file, header=0)
df_price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   price        25209 non-null  object
 2   nbhood_full  25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB

In [42]:
# importing tsv
file = 'data/airbnb_last_review.tsv'
df_last_rev = pd.read_csv(file, header=0, sep='\t')
df_last_rev.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   host_name    25201 non-null  object
 2   last_review  25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB

Merge / Join df

In [43]:
df_merged = df_room_type.merge(df_price, on='listing_id')
df_merged = df_merged.merge(df_last_rev, on='listing_id')
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25209 entries, 0 to 25208
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   description  25199 non-null  object
 2   room_type    25209 non-null  object
 3   price        25209 non-null  object
 4   nbhood_full  25209 non-null  object
 5   host_name    25201 non-null  object
 6   last_review  25209 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.5+ MB

In [44]:
df_merged.head()

   listing_id  ...   last_review
0        2595  ...   May 21 2019
1        3831  ...  July 05 2019
2        5099  ...  June 22 2019
3        5178  ...  June 24 2019
4        5238  ...  June 09 2019

[5 rows x 7 columns]

# Limpieza

In [45]:
# Nombres de host nulos
df_merged['host_name'].isna().sum()

8

In [46]:
# Número de categorías en room_type

df_merged['room_type'] = df_merged['room_type'].str.lower()
df_merged['room_type'] = df_merged['room_type'].astype('category')
df_merged['room_type'].value_counts()

entire home/apt    13266
private room       11356
shared room          587
Name: room_type, dtype: int64

In [47]:
# Comprobar valores únicos de linsting_id
df_merged['listing_id'].duplicated().any()

False

In [48]:
# Convertir columna price a int
df_merged['price'] = df_merged['price'].str.strip(' dollars')
df_merged['price'] = df_merged['price'].astype('int')

In [49]:
df_merged['price'].values

array([225,  89, 200, ..., 235, 100,  30])

In [50]:
# Estandarizar fechas de last_review
df_merged['last_review'] = pd.to_datetime(df_merged['last_review']).dt.date
df_merged['last_review'].values

array([datetime.date(2019, 5, 21), datetime.date(2019, 7, 5),
       datetime.date(2019, 6, 22), ..., datetime.date(2019, 7, 7),
       datetime.date(2019, 7, 7), datetime.date(2019, 7, 8)], dtype=object)

In [51]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25209 entries, 0 to 25208
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   description  25199 non-null  object
 2   room_type    25209 non-null  category
 3   price        25209 non-null  int64
 4   nbhood_full  25209 non-null  object
 5   host_name    25201 non-null  object
 6   last_review  25209 non-null  object
dtypes: category(1), int64(2), object(4)
memory usage: 1.4+ MB

# Insights

## What are the dates of the earliest and most recent reviews? Store these values as two separate variables with your preferred names.

In [52]:
min_rev = min(df_merged['last_review'])
print(min_rev)

2019-01-01

In [53]:
max_rev = max(df_merged['last_review'])
print(max_rev)

2019-07-09

## How many of the listings are private rooms? Save this into any variable.

In [54]:
pr_num = df_merged['room_type'].eq('private room').sum(axis=0)
pr_num

11356

## What is the average listing price? Round to the nearest two decimal places and save into a variable.

In [55]:
avg_list_price = df_merged['price'].mean().round(2)
avg_list_price

141.78

# Create a df

## Combine the new variables into one DataFrame called review_dates with four columns in the following order: first_reviewed, last_reviewed, nb_private_rooms, and avg_price. The DataFrame should only contain one row of values.

In [56]:
review_dates = pd.DataFrame({
    'first_reviewed': [min_rev],
    'last_reviewed': [max_rev],
    'nb_private_rooms': [pr_num],
    'avg_price': [avg_list_price]
})

review_dates.head()

  first_reviewed last_reviewed  nb_private_rooms  avg_price
0     2019-01-01    2019-07-09             11356     141.78